const { MongoClient } = require("mongodb");

const locations = [
  {
    src: "cascatapincho.jpg",
    title: "Cascata do Pincho, Amonde",
    description: "Description for image 1",
    typeicon: "Natureza",
    types: ["Praia", "Rio", "Lagoa", "Merendas", "Parque", "WC", "Vigiada"],
    latitude: 41.7782,
    longitude: -8.5331,
  },
  {
    src: "castelolindoso.jpg",
    title: "Castelo do Lindoso, Lindoso",
    description: "Description for image 2",
    typeicon: "Cultura",
    types: ["Cultura", "Monumento"],
    latitude: 41.8206,
    longitude: -8.2045,
  },
  {
    src: "cascatarodeiro.jpg",
    title: "Cascata do Rodeiro, Soajo",
    description: "Description for image 3",
    typeicon: "Natureza",
    types: [
      "Praia",
      "Rio",
      "Parque",
      "Caminhada",
      "Natureza",
      "Merendas",
      "WCprox",
      "Bar",
      "Dog",
    ],
    latitude: 41.8626,
    longitude: -8.3128,
  },
  {
    src: "cascatapereiro.jpg",
    title: "Cascata do Pereiro",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Merendas",
      "Lagoa",
      "Praia",
      "Crianças",
      "Facilacesso",
      "Rio",
      "Mesas",
    ],
    latitude: 41.77278073067233,
    longitude: -8.7300894705241,
    url: "file:///C:/Users/sarav/Desktop/locais/index.html#vermaiscontainer26",
  },
  {
    src: "esturranha.jpg",
    title: "Lagoa da Esturranha",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Lagoa",
      "Praia",
      "Cultura",
      "Crianças",
      "Facilacesso",
      "Banho",
      "Natureza",
      "PoucoMove",
      ,
      "Animal",
      "Caminhada",
      "Tour",
    ],
    latitude: 41.800143968318324,
    longitude: -8.794582793252912,
    url: "https://www.booking.com/",
  },
  {
    src: "lagoapontesaojoao.jpg",
    title: "Lagoa da Ponte de São João",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Lagoa",
      "Trilho",
      "Cascatamerendas",
      "Praia",
      "Cultura",
      "Banho",
      "Natureza",
      "Merendas",
      "Rio",
      "Meditação",
      "Gratuito",
    ],
    latitude: 41.87608718573341,
    longitude: -8.733497258839384,
    url: "https://www.booking.com/",
  },
  {
    src: "poçonegroareosa.jpg",
    title: "Poço Negro",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Lagoa",
      "Trilho",
      "Cascatamerendas",
      "Praia",
      "Cultura",
      "Facilacesso",
      "Banho",
      "Circular",
    ],
    latitude: 41.72401433256495,
    longitude: -8.846865722653872,
    url: "https://www.booking.com/",
  },
  {
    src: "poçoazulafife.jpg",
    title: "Poço Azul",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Facilacesso",
      "Banho",
    ],
    latitude: 41.771876813022715,
    longitude: -8.844525414681744,
    url: "https://www.booking.com/",
  },
  {
    src: "passadiçossaojoao.jpg",
    title: "Passadiços da Ribeira S. João",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Trilho",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Curto",
      "Crianças",
      "Facilacesso",
      ,
      "BeiraRio",
    ],
    latitude: 41.839517346252556,
    longitude: -8.594436342254507,
    url: "https://www.booking.com/",
  },
  {
    src: "cascatafojo.png",
    title: "Cascata do Fojo",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Crianças",
      "Facilacesso",
    ],
    trailDistance: 50,
    latitude: 42.046280323756825,
    longitude: -8.528294090124739,
    url: "https://www.booking.com/",
  },
  {
    src: "cascatalaboreiro.jpg",
    title: "Cascata do Laboreiro",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura"],
    trailDistance: 150,
    latitude: 42.030356716004555,
    longitude: -8.154909796231204,
    url: "https://www.booking.com/",
  },
  {
    src: "poçobento.jpg",
    title: "Cascata do Bento e das Canejas",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    trailDistance: 10,
    latitude: 41.88316731565923,
    longitude: -8.249727940823377,
    url: "https://www.booking.com/",
  },
  {
    src: "poçocontador.jpg",
    title: "Poço do Contador",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    trailDistance: 20,
    latitude: 41.99038839592727,
    longitude: -8.159124093252911,
    url: "https://www.booking.com/",
  },
  {
    src: "poçogola.jpg",
    title: "Poço da Gola",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Crianças",
      "Facilacesso",
      "Banho",
    ],
    trailDistance: 100,
    latitude: 41.85798148522336,
    longitude: -8.222344095665521,
    url: "https://www.booking.com/",
  },
  {
    src: "lagoasgrade.jpg",
    title: "Lagoas de Grade",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    latitude: 41.8768969654397,
    longitude: -8.368828769433827,
    url: "https://www.booking.com/",
  },
  {
    src: "praiamanadelo.jpg",
    title: "Praia Fluvial do Manadelo",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Praia",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Facilacesso",
      "Banho",
    ],
    latitude: 41.798566588766576,
    longitude: -8.739639125482277,
    url: "https://www.booking.com/",
  },
  {
    src: "poçonegrosoajo.jpg",
    title: "Poço Negro",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Facilacesso",
      "Banho",
    ],
    latitude: 41.87851106001374,
    longitude: -8.25691649423439,
    url: "https://www.booking.com/",
  },
  {
    src: "cascatarodeiro.jpg",
    title: "Cascata do Rodeiro",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    latitude: 42.05331524414384,
    longitude: -8.133904449076537,
    url: "https://www.booking.com/",
  },
  {
    src: "poçasmalho.jpg",
    title: "Poças do Malho",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Merendas",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    latitude: 41.92348901113711,
    longitude: -8.209202335563628,
    url: "https://www.booking.com/",
  },
  {
    src: "poçocaldeiras.jpg",
    title: "Poço das Caldeiras",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Merendas",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura", "Banho"],
    latitude: 41.94107517777134,
    longitude: -8.427679084640163,
    url: "https://www.booking.com/",
  },
  {
    src: "lagoatravanca.jpg",
    title: "Lagoa da Travanca",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Praia",
    types: ["Cascata", "Trilho", "Merendas", "Praia", "Cultura"],
    latitude: 41.904052043496456,
    longitude: -8.314365409725378,
    url: "https://www.booking.com/",
  },
  {
    src: "poçomantas.jpg",
    title: "Poço das Mantas",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Natureza",
    types: [
      "Cascata",
      "Trilho",
      "Cascatamerendas",
      "Lagoa",
      "Praia",
      "Cultura",
      "Crianças",
      "Facilacesso",
      "Banho",
    ],
    latitude: 41.88071776184172,
    longitude: -8.268175308537808,
    url: "https://www.booking.com/",
  },
  {
    src: "lagoadruidas.jpg",
    title: "Lagoa dos Druidas",
    description: "Praia Fluvial com lagoa para banhos",
    typeicon: "Cultura",
    types: [
      "Cascata",
      "Trilho",
      "Merendas",
      "Praia",
      "Cultura",
      "Banho",
      "Supermercado",
    ],
    latitude: 41.93571863218769,
    longitude: -8.234062466264563,
    url: "https://www.booking.com/",
  },
];

async function insertData() {
  const uri = "mongodb://localhost:27017"; // Replace with your MongoDB URI
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const database = client.db("locationsdatabase"); // Replace with your database name
    const collection = database.collection("locations");

    // Add like/dislike count to each location
    const locationsWithCounts = locations.map((location) => ({
      ...location,
      likes: 0,
      dislikes: 0,
    }));

    await collection.insertMany(locationsWithCounts);
    console.log("Data inserted successfully");
  } finally {
    await client.close();
  }
}

insertData().catch(console.error);
